### PR TITLE
Fix #243 element should only implicitly wait when use_implicit_waits = true 

### LINKED ISSUE #243: element(s) use implicit waits regardless of setting
## Summary
`@search_page.search_results` waits for Capybara.default_max_wait_time when `SitePrism.use_implicit_waits = false`

## Environment
- Operating System (Mac)
- site_prism master at c9526bf9fe38039973ed339d6fbb05a03deb7b20     capybara (2.18.0)
- How you're interacting with the Framework - Using the builtin cucumber tests
- Firefox 59.0.2

## Expected Behavior
Implicit waits should not be performed when disabled by `config.use_implicit_waits = false`

### Detail
Per the readme:
> By default, SitePrism element and section methods do not utilize
> Capybara's implicit wait methodology and will return immediately if
> the element or section requested is not found on the page.  Add the
> following code to your spec_helper file to enable Capybara's implicit
> wait methodology to pass through:
> 
> ```ruby
> SitePrism.configure do |config|
>   config.use_implicit_waits = true
> end
> ```
> 
> This enables you to replace this:
> 
> ```ruby
> # wait_until methods always wait for the element to be present on the page:
> @search_page.wait_for_search_results
> 
> # Element and section methods do not:
> @search_page.search_results
> ```
> 

with this:

```ruby
# With implicit waits enabled, use of wait_until methods is no longer required. This method will
# wait for the element to be found on the page until the Capybara default timeout is reached.
@search_page.search_results
```

## Actual Behavior
For something like `@search_page.search_results` implicit waits **are** performed.

## Steps to reproduce

Add the following cucumber steps:

```rb
+
+Then(/^implicit waits are not enabled$/) do
+  expect(SitePrism.use_implicit_waits).to eq false
+end
+
+Then(/^the slow element is not waited for$/) do
+  start_time = Time.now
+  @test_site.home.some_slow_element
+  expect(Time.now - start_time).to be < 0.5
+end


# and features/waiting.feature
+  Scenario: Elements Are Not Waited For By
+    When I navigate to the home page
+    Then the slow element is not waited for
+    And implicit waits are not enabled

```

Run `bundle exec cucumber`

Observe: 

```
  Scenario: Elements Are Not Waited For By  # features/waiting.feature:53
    When I navigate to the home page        # features/step_definitions/navigation_steps.rb:3
    Then the slow element is not waited for # features/step_definitions/page_element_interaction_steps.rb:169
      expected: < 0.5
           got:   2.034348 (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/page_element_interaction_steps.rb:172:in `/^the slow element is not waited for$/'
      features/waiting.feature:55:in `Then the slow element is not waited for'
    And implicit waits are not enabled      # features/step_definitions/page_element_interaction_steps.rb:164
```

See also: https://github.com/natritmeyer/site_prism/commit/7c59938cc91bb6ad0b22c18861227f0dc2479d67

The above indicates that despite implicit waits being **disabled** they were in fact used.  (some_slow_element waits 2s before appearing on page.)

### PR DESCRIPTION
**Pull request by tgaff**
This is a fix for #243 - _please_ see there for extensive details.  
TLDR;
`@search_page.search_results` waits for Capybara.default_max_wait_time when `SitePrism.use_implicit_waits = false` our Readme says that shouldn't happen.

### CODE REVIEW

**Comment by tgaff** [comment]
Please note that this PR is based off of #251 as it affects related functionality and I'm hoping to save myself another re-write.
I had intended to wait until that was merged before finishing this but 251 was(is?) blocked by #226 and this blocks #242.
(If that's not confusing enough 😅 make sure you read the real issue in #243, which this solves! 😅)

Happy to re-base this if the other gets merged.

**Comment by luke-hill** [comment]
Hi Travis. My rough plan for "existing PRs" all with ID 252 or less.

PRs submitted
236 - spec rewrite using shared examples (me)
244 - this PR (you)
248 - minor waiting cleanup (me)
249 - cucumber cleanup / feng shui (me)
250 - allow search arguments to be set inside a class (root_element locators) (another contributor)
251 - tidying up wait logic (you)
252 - new feature (elements present) (me)

Current release
236 / 249 (Only if either of them are reviewed and signed off before Wednesday next week)
251 - This I need to review (I believe it is now in a state ready to be reviewed / merged?)

V2.14
248 - definitely
244 (This PR, although if you feel as though you can clean it up and fix)
250 - if contributor can explain a couple of confusing areas
252 - tiny PR new feature

**Comment by luke-hill** [comment]
In that case we'll just aim to get 236/249 in this release (As theyre both refactors), and I'll push 251 down into next release candidate as well.

**Comment by luke-hill** [comment]
Is the plan for this PR wait until your other PR is merged and then rebase / merge with master. Or would it be easier to rebuild this one from cherry-picks?

**Comment by tgaff** [comment]
@luke-hill yes, they've been moving slowly and continuing to rebase didn't seem like a good use of time

**Comment by luke-hill** [comment]
Top stuff. Thanks for the help. Much appreciated.

In a few days time I'm gonna go on a decent merge spree. Start prepping for the next version. 

I've been away for 2 weeks, so hopefully stuff is now nicely moved on in my absence PR wise.

**Comment by shaneog** [comment]
Any update on this?

**Comment by luke-hill** [comment]
Hi @shaneog A fix will be in place shortly. It's fairly high on the list of priorities (As you can tell by it now being the only PR left).

However due to some architectural changes. The best way to implement this is to cherry-pick the commits. Which I will be doing as my next feature (I've spoke to the author briefly about this)

The next official RC will have this in, and a release date for that will be forthcoming (ETA is unknown atm)

**Pull request closed without merging**
