### PR TITLE
Configure travis to test with rspec3 (default) and rspec2 for great compatibility

### LINKED ISSUE #78: configure travis.yml to run tests with rspec2 and rspec3

### PR DESCRIPTION
**Pull request by tgaff**
Resolves #78

### CODE REVIEW

**Comment by luke-hill** [comment]
This is one of a few PR's raised which I'm looking into, and just generally giving a "bump".

Could you provide an update if at all possible into what you want to do with this PR (I'm aware it's been left a while)

If you no longer feel this is a relevant PR, or is too outdated. Then please close.
If you feel as though this PR isn't actionable anymore, then please close.

Thanks for your contribution.

Note: I don't think supporting RSpec 2 is now really required (But at the time probably was).

**Comment by tgaff** [comment]
It's been open a long time and the repo author apparently never took interest.  Closed.

**Comment by luke-hill** [comment]
Apologies for that. I will be running this gem hopefully going forwards. So sorry for your dis-interest.

As a rough roadmap idea (I've got every single Issue / PR color co-ordinated at my end), I'm going to address each PR according to its status.

The initial release plan is just to cut an almost unchanged 2.9.1 and then a 2.10 both in the next 1-2months. Once both of those are cut, then PR's will start to hopefully get merged in again.

Sorry again for the hassle, I'm aware this is a bit of a dead dodo.

**Comment by tgaff** [comment]
@luke-hill If you think you could use some help on something let me know.  I've got a little time right now and as long as things are going to move along I'd be happy to contribute.  

As a starter, it looks like the tests on master are failing.  Have you taken a look at that yet?

**Pull request closed without merging**
