### PR TITLE
Remove configuration for raise_on_wait_for - V3

### PR DESCRIPTION
**Pull request by luke-hill**
For now just an MVP implementation, but this removes `raise_on_wait_for` as a configuration option. These are now hard-coded

### CODE REVIEW

**Comment by luke-hill** [comment]
ping @tgaff @ineverov if you have time (The first piece of work to clean up the API)
@tmertens if you're interested take a look

**Comment by tgaff** [comment]
You're too fast @luke-hill  !

**Comment by tgaff** [comment]
This simplified quite a bit! :-)

**Comment by luke-hill** [comment]
Hehe sorry Travis. The other PR Is operas I’ve not fixed it up yet.

**Pull request merged**
