### PR TITLE
fixed method name collision with rspec

### PR DESCRIPTION
**Pull request by tobithiel**
I ran into the same issues as people in #95 and #102. These changes fix the name collision by explicitly selecting the `page` as the recipient of the method calls.
This only fixes the name collisions I ran into, not sure if there more locations where this happens.
Please let me know what you think!

### CODE REVIEW

**Comment by tobithiel** [comment]
Not sure why it fails on `bundle install` ... Seems unrelated.

**Comment by natritmeyer** [comment]
Hi @tobithiel, I've fixed the build issue which you ran into. Could you add a test to this PR showing that the name collision is fixed? Thanks :)

**Comment by tobithiel** [comment]
@natritmeyer Thanks! I've added a test to trigger the issue I was experiencing.

**Comment by scalixte-mdsol** [comment]
@tobithiel @natritmeyer I verified the issue is fixed for me on this branch. How soon can this PR be resolved as I am impeded by this progress?

Thank you both.

**Comment by markpfletcher** [comment]
It would be great to get this PR merged - I'm having to apply some monkey patches to my project in the mean time...

**Comment by Carlbc18** [comment]
Id plus one the above comment (+1)

**Comment by natritmeyer** [comment]
I'll take a look tonight

**Comment by lefty1975** [comment]
I know this change more than a year old, but I have 
` site_prism (2.9)
      addressable (>= 2.3.3, < 3.0)
      capybara (>= 2.1, < 3.0)`
And I still see:
`def find_all(*find_args)
      all(*find_args)
    end`
Did this change make it into the version I listed above?

**Pull request merged**
